params:
  model_type: gradient_boosting
  model_params:
    n_estimators: 300
    learning_rate: 0.03
    max_depth: 3
    random_state: 42


# params:
#   model_type: decision_tree
#   model_params:
#     max_depth: 10
#     min_samples_split: 15
#     random_state: 42


# params:
#   model_type: logistic_regression
#   model_params:
#     penalty: elasticnet
#     C: 0.9
#     l1_ratio: 0.5
#     solver: saga
#     max_iter: 2000
#     random_state: 42


# params:
#   model_type: random_forest
#   model_params:
#     n_estimators: 300
#     max_depth: 12
#     random_state: 42
#     n_jobs: -1